### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by Arlanthir** [christopherthielen/typedoc-plugin-external-module-name#11]
Is it possible to declare/reference submodules, e.g. `thing1.subthing1`?

If so, how can we do it (I tried the obvious `@module thing1.subthing1` and only the first part is identified as the module name)?

If not, is it a design decision not to support it?

Thanks

**Comment by christopherthielen** [comment]
This is something that Typedoc itself would have to support.  I think you can use slashes though:

```js
@module thing1/subthing
```

**Comment by Arlanthir** [comment]
Because the slashes didn't work, I decided to implement submodules (with '.') in a fork: https://github.com/Arlanthir/typedoc-plugin-external-module-name/tree/submodules

Is this something you would be interested in merging, i.e., should I make a PR?

**Comment by christopherthielen** [comment]
What does the typedoc output look like with this change?  I'm definitely open to merging it.

**Comment by Arlanthir** [comment]
As promised:

![parent](https://user-images.githubusercontent.com/2780456/46611810-c9c25a80-cb06-11e8-9ef8-40dd3d285e5b.png)
![child](https://user-images.githubusercontent.com/2780456/46611811-c9c25a80-cb06-11e8-9c8a-aac811fc217e.png)

**Comment by stevenalanstark** [comment]
This addition breaks reflections, doesn't work in all cases, and causes confusion between 'internal' and 'external' modules. this should be reverted until resolved.
