### ISSUE TITLE
Namespaces are need to use this plugin?

### ISSUE THREAD

**Issue by caiorcferreira** [christopherthielen/typedoc-plugin-external-module-name#13]
Hello,

I'm playing with typedoc and finded this module very useful, but I don't know if I'm using it properly. For reference, here is my sample code:

_//File: users.module.ts_

```ts
import { Module } from '@nestjs/common';
import { UsersController } from './users.controller';

/**
 * @module Users
 * @preferred
 * 
 * Module to handle users.
 */
/**
 * Users Nest module.
 * 
 * @class UsersModule
 */
@Module({
  controllers: [ UsersController ]
})
export class UsersModule {}
```

_//File: users.controller.ts_

```ts
import { Controller, Get, Post, HttpStatus } from '@nestjs/common';
import { Response, Request, NextFunction } from 'express';

/**
 * @module Users
 */
/**
 * Controller for the users resource.
 * 
 * @class UsersController
 */
@Controller()
export class UsersController {

  /**
   * Get all users registred.
   * 
   * @param {Request} req        Request object
   * @param {Response} res       Response object
   * @param {NextFunction} next          Next middleware to be executed
   * @memberof UsersController
   */
  @Get('users')
  getAllUsers(req: Request, res: Response, next: NextFunction){
    res.status(HttpStatus.OK).send({
      id: 1, name: 'Caio'
    });
  }

  @Get('users/:id')
  getUser() {}

  @Post('users')
  addUser() {}
}
```

I'm using a framework called [Nest](http://nestjs.com/), but I don't know if it's relevant.
I was thinking if its plugin needs of formal namespaces to proper work, or if I'm messing with something else.

Thanks for all the effort, and I'm sorry for the formating, I included the code in the quotation but its getting weird.

**Comment by christopherthielen** [comment]
The plugin doesn't need namespaces (assuming you mean typescript namespaces).  I don't see any namespaces in your example. 

Sorry for the late response.   If you're still interested, can you provide more details?
