### ISSUE TITLE
Can not use module names with dots

### ISSUE THREAD

**Issue by Ernie23** [christopherthielen/typedoc-plugin-external-module-name#18]
I am trying to achieve module names with dots e.g.:    LT.Graphics

![image](https://user-images.githubusercontent.com/5499652/37394045-207f1f8a-2773-11e8-8cfc-554ee4337304.png)

Generated help file only shows LT. The rest of the name (.Graphics) is missing.

![image](https://user-images.githubusercontent.com/5499652/37394178-7d2dd14a-2773-11e8-8ecd-09a123fb1523.png)

My opinion your regex expression does not allow dots.

Can you please add dot ( . ) in your regex expression as valid character?

**Comment by pranavjindal999** [comment]
I was also looking for the same.

And then I tried using / but that makes another module. I was looking for nested modules.
