### ISSUE TITLE
Plugin not working with typescript 2.0.3

### ISSUE THREAD

**Issue by emilekberg** [christopherthielen/typedoc-plugin-external-module-name#2]
There seem to be an issue where the plugin does not work for me when using typescript 2.0.3. I fixed this by removing the ones this plugin installed in the node_modules folder, making it use a higher typedoc and typescript version, i.e. the ones in the root node_modules folder.

**Comment by emilianosantucci** [comment]
Same issue here.
@emilekberg, for *root* do you intend global one?

**Comment by emilekberg** [comment]
@emilianosantucci no, i used an local installation, so what i meant was the one in the node_modules next to the package.json. I guess the same thing goes for the global one though.

**Comment by christopherthielen** [comment]
This should be fixed now.  See #4 
The plugin now requires a `peerDependency` of  typedoc ^0.5.3

**Comment by unsafecode** [comment]
@christopherthielen Nice, it worked once updated. Thanks!

**Comment by christopherthielen** [comment]
Yay!!!
