### ISSUE TITLE
Doesn't seem to be working with typedoc 0.11.1 and typescript 2.7

### ISSUE THREAD

**Issue by ovasquez** [christopherthielen/typedoc-plugin-external-module-name#21]
Is there something else that needs to be done besides what is specified in the readme? The plugin does get loaded but it doesn't seem to do anyting:
```
npx typedoc src --out web
Loaded plugin typedoc-plugin-external-module-name

Using TypeScript 2.7.2 from S:\Workspace\node_modules\typedoc\node_modules\typescript\lib
Rendering [========================================] 100%

Documentation generated at S:\Workspace\web
```

I've been trying to generate per module documentation in a simple project with no success. I tried to reduce the documentation to the minimum (keeping mostly just the `@module` tags) to eliminate the problem but I still get separate modules for all files.

**Comment by christopherthielen** [comment]
Hi, I've added an e2e test for typedoc 0.11.1 and typescript 2.7 https://github.com/christopherthielen/typedoc-plugin-external-module-name/commit/c1bec4110d2f86d7f5bde270455f9d60396bb6e2

Seems to work in there.  Can you show some more details so I can help diagnose?

**Comment by ovasquez** [comment]
Hi @christopherthielen, after a while of debugging I was able to reproduce the issue.

## Issue
Basically when a file has a comment header with a statement other than the `@module` it fails to recognize it as a module. In our case all files have a license header, adding a header is enough for it to be ignored by this plugin.

I traced the issue to the [`onDeclaration`](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/master/plugin.ts#L66) function of the `plugin.ts` file. Whet it gets the raw comment it just takes the first one, and because the first one is the license header it ignores the `@module` statement.

For now I think updating the documentation to clarify this could be enough.
I'm not sure if this is a fixable issue, please let me know if there's anything else I can help with.

## Steps to reproduce
Here's how I modified the file `file1.ts` to confirm this issue.
```ts
/**
 * Licsense MIT
 */

/**
 * @module root
 */

/** This is in the root module */
export class File1 {}
```

**Comment by christopherthielen** [comment]
@ovasquez interesting, thanks for investigating and reporting back!

If you can think of a reasonable way to fix the plugin to read  from all top level comments, I'll gladly merge a PR.  For now, I'm updating the README.

**Comment by Gerrit0** [comment]
As of TypeDoc 0.15.6, TypeDoc will take the module comment marked with `@packageDocumentation` at the top of the file, even if it isn't the first comment. (So long as it appears before any TS statements)
