### ISSUE TITLE
Module comment not rendering

### ISSUE THREAD

**Issue by tjwelde** [christopherthielen/typedoc-plugin-external-module-name#300]
Hey, thanks for this module.

As described here: https://github.com/christopherthielen/typedoc-plugin-external-module-name#thing2quxts, it should be possible to add a module comment.
I tried putting the comment on top and below of `@module` and added `@preferred`, but no comment is rendering.

The command i am using is: `typedoc --theme default --out docs`
typedoc: v0.14.2
typedoc-plugin-external-module-name: v2.0.0

**Comment by thierrymichel** [comment]
Hi here,

Finally, I made it work with the addition of an empty comment:
```
/**
 * This comment will be printed
 *
 * @module my/module
 * @preferred works too
 */

/***/
```

I've found that [this line](https://github.com/TypeStrong/typedoc/blob/cdf3acdd5e56b4fb6683f2ddb8067220e44dde1b/src/lib/converter/factories/comment.ts#L90) was returning no comment for the reflection (no idea why).
With 2 comments, reflection have the right comment and [this code](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/master/plugin.ts#L81) is executed.

**Comment by HermitSun** [comment]
I met this problem as well, it seems that the problem still exists. And @thierrymichel's solution works for me.
And still [this line](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/factories/comment.ts#L107) returns no comment. That's strange.

**Comment by christopherthielen** [comment]
Try using the new [`@packageDocumentation` tag from typedoc 0.15.8](https://typedoc.org/guides/doccomments/#files)

```
/**
 * @packageDocumentation
 * @module foo
 */
```

**Comment by christopherthielen** [comment]
also please upgrade to the new version  https://github.com/christopherthielen/typedoc-plugin-external-module-name/releases/tag/2.2.1
