### ISSUE TITLE
Module types reflection is broken with this plugin

### ISSUE THREAD

**Issue by manrueda** [christopherthielen/typedoc-plugin-external-module-name#313]
If the code being documented has a structure like the [this one](https://gist.github.com/ManRueda/bf6914acec617d3bb579e9a1f95f8a63) (*gist doesn't allow folder, so i mimic it with dashes (-) instead of (/)*).

I think that the issue is here: https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/master/plugin.ts#L132, this line removes the declaration of the `sub/index.ts` module that is being imported in the `index.ts` file.

The type will get resolve as a absolute path because typedoc can not found that module anymore.

![image](https://user-images.githubusercontent.com/2576444/55261172-9902e880-5240-11e9-9fbb-61a87b93b3a9.png)

**Comment by stevenalanstark** [comment]
try with typedoc `0.13.0`, I had similar issues with `0.14.0` and later.

**Comment by christopherthielen** [comment]
released https://github.com/christopherthielen/typedoc-plugin-external-module-name/releases/tag/2.2.1
