### ISSUE TITLE
Using submodules fails on getKindString

### ISSUE THREAD

**Issue by stevenalanstark** [christopherthielen/typedoc-plugin-external-module-name#332]
Reference: PR #213 

Submodules working is very hit and miss for me. 

In my project, I do not have folders like: 

`src\comp\index.ts`

I just have:

```
src\comp\thing1.ts
src\comp\thing2.ts
src\comp\sub\thing1.ts
```

In some cases, submodules will just work without an issue, but in most cases I am presented with the following error: 

```
node_modules/typedoc/dist/lib/converter/plugins/GroupPlugin.js:90
        str = str.replace(/(.)([A-Z])/g, (m, a, b) => a + ' ' + b.toLowerCase());

TypeError: Cannot read property 'replace' of undefined
```

When it fails I know it's looking for the base module key. 

ex: a submodule for `Chips.entities` would fail on `Chips` as the value for `kind` ( aka `b` ), it is not found in the `index_1.ReflectionKind` array

NOTE: I never see a string value for `kind` except for when it errors, every other case it's a short int

Here is some debugging console.log output:

```

--------------KIND--------------
Chips
--------------index_1.ReflectionKind--------------
{ '0': 'Global',
  '1': 'ExternalModule',
  '2': 'Module',
  '3': 'SomeModule',
  '4': 'Enum',
  '16': 'EnumMember',
  '32': 'Variable',
  '64': 'Function',
  '128': 'Class',
  '256': 'Interface',
  '384': 'ClassOrInterface',
  '512': 'Constructor',
  '1024': 'Property',
  '1056': 'VariableOrProperty',
  '2048': 'Method',
  '2112': 'FunctionOrMethod',
  '4096': 'CallSignature',
  '8192': 'IndexSignature',
  '16384': 'ConstructorSignature',
  '32768': 'Parameter',
  '65536': 'TypeLiteral',
  '131072': 'TypeParameter',
  '262144': 'Accessor',
  '524288': 'GetSignature',
  '1048576': 'SetSignature',
  '1601536': 'SomeSignature',
  '2097152': 'ObjectLiteral',
  '4194304': 'TypeAlias',
  '8388608': 'Event',
  Global: 0,
  ExternalModule: 1,
  Module: 2,
  Enum: 4,
  EnumMember: 16,
  Variable: 32,
  Function: 64,
  Class: 128,
  Interface: 256,
  Constructor: 512,
  Property: 1024,
  Method: 2048,
  CallSignature: 4096,
  IndexSignature: 8192,
  ConstructorSignature: 16384,
  Parameter: 32768,
  TypeLiteral: 65536,
  TypeParameter: 131072,
  Accessor: 262144,
  GetSignature: 524288,
  SetSignature: 1048576,
  ObjectLiteral: 2097152,
  TypeAlias: 4194304,
  Event: 8388608,
  ClassOrInterface: 384,
  VariableOrProperty: 1056,
  FunctionOrMethod: 2112,
  SomeSignature: 1601536,
  SomeModule: 3 }
```

It seems clear to me that `Chips` is the wrong value for kind; it's a module name and not a kind.

**Comment by stevenalanstark** [comment]
I have determined that this is a typedoc version issue. It seems that things no longer work on the newest typedoc versions

typedoc `1.13.0` is working, but `1.14.0` and later is not.

**Comment by rmainseas** [comment]
I'm having this same issue and using typedoc 0.14.2. However, on one branch of my application it works - but on another it doesn't.

I can't quite pin down what's breaking things, except that as @stevenalanstark pointed out it seems to be trying to use the actual module name as a type rather than "module".

**Comment by stevenalanstark** [comment]
I think this has to do with not being able to know which code is internal and which is external. When using `0.14.0`, half my code is marked as 'internal' and half as 'external' when viewing the HTML output. A glance over the JSON output looks like almost everything is 'external', with `isExternal` set to true. 

The submodule code is also explicitly setting submodule items as external.

Using the module name instead of the is *should* be fine, as the map is duplicated to to allow lookups by either key or value. What I've seen is that the module just doesn't exist in the list at all.

**Comment by Arlanthir** [comment]
Thanks for the report and the analysis.
Since it's been a few days and I was the original author of the feature, I just wanted to say I'm looking into it but I have no relevant news yet.

The new typedoc version breaks my team's project as well with the same error, although the dimension of the project makes it hard to debug. Simpler example projects are working fine, so I'll need a bit more time to understand what's actually happening. Any simple test cases that reproduce the behavior are welcome!

**Comment by stevenalanstark** [comment]
@Arlanthir Thank you so much for this PR!

I have tested it, and it worked as expected. It seems this resolves the issues with my project completely. Well done!

**Comment by rmainseas** [comment]
@stevenalanstark Does this mean that the plugin now supports nested sub-modules?

**Comment by christopherthielen** [comment]
released https://github.com/christopherthielen/typedoc-plugin-external-module-name/releases/tag/2.2.1
