### ISSUE TITLE
Breaking Change incoming from Typedoc master change to getJSDocCommentRanges

### ISSUE THREAD

**Issue by stevenalanstark** [christopherthielen/typedoc-plugin-external-module-name#337]
This commit to typedoc will break things once it's pulled in here:
 
https://github.com/TypeStrong/typedoc/commit/26202da4eeed8cae80e167a46e0dad9a4543799d#diff-166f9f38d3914bf0531440336664ea68R102

Currently, this isn't a dependency on this project.

In my fork, I have fixed this by copying the whole `getJSDocCommentRanges` into `getRawComments`, but that is very much overkill. 

It looks as if the intent is to make this function internal only, and not part of the _ts API

**Comment by Neloreck** [comment]
Seems like this issue can be transformed to bug.
Latest typedoc (0.15.0) does not work with latest plugin version (2.1.0).

You have to create comment right after @module declaration to detect it.
(reference: https://github.com/christopherthielen/typedoc-plugin-external-module-name/issues/6)

**Comment by pmconne** [comment]
Does anyone have a sense of how feasible it is to fix this? I am completely unfamiliar with typedoc or this plugin but if nobody else is looking into it I could have a go. We updated to TypeScript 3.7, which requires us to use the newest version of typedoc, which prevents us from using this plugin.

**Comment by christopherthielen** [comment]
fixed in https://github.com/christopherthielen/typedoc-plugin-external-module-name/pull/395/commits/e76b05263d01ccad6e538c651851dcb3c039cfbf

**Comment by williamkbentley** [comment]
Will we need @packageDescription?

**Comment by christopherthielen** [comment]
released https://github.com/christopherthielen/typedoc-plugin-external-module-name/releases/tag/3.0.0

**Comment by christopherthielen** [comment]
@williamkbentley  Yes.

 It looks like that's the direction the TypeDoc team is taking that issue so that's what I'm recommending as well.  I've updated the README and release notes to indicate this.

**Comment by williamkbentley** [comment]
Works for me! Thanks for the hard work
