### ISSUE TITLE
not working with TypeDoc 0.15.0

### ISSUE THREAD

**Issue by simllll** [christopherthielen/typedoc-plugin-external-module-name#350]
This plugin somehow does not work with latest typedoc 0.15 version. It still works with the older one, but only if I remove the typescript 3.5.x dependency to get my scripts compiled.

I get the output that the module is loaded when I just compiling:
Loaded plugin /home/simon/Dev/Web/hokify-server/node_modules/typedoc-plugin-external-module-name

I run the command without any special arugments, have tested it with several different appraoches already though:
 typedoc --out ./docs ./src/

I have several  
```
/**
 * @module MyModule1
*/
```

definitions as first line in several files, but the output modules are not comibed at all (every file is a single module listed in globals), it's just the same as without the module. Is there an issue with 0.15 or do I miss something here to get this running?

Just to clarify: I first thought I cannot test it with typedoc 0.14, but as it turns out, the only problem was the older typescript version that is defined in typedoc package.json. If I remove the reference and let typedoc let use my latest installed typescript (3.6.3) everything works fine with 0.14.2.

Thanks a lot
Simon

**Comment by Neloreck** [comment]
https://github.com/christopherthielen/typedoc-plugin-external-module-name/issues/337

:(

**Comment by Oblarg** [comment]
The workaround mentioned in #337 does indeed allow typedoc to recognize the module specification, but it seems to ignore any module documentation text even if `@preferred` is present.  Any ideas?

**Comment by morganzysman** [comment]
I have the same issue, Anyone having a solution here ?

**Comment by pmconne** [comment]
@morganzysman see #337 - currently the only "fix" I know of is to stick another jsDoc comment directly below the @module comment.
```ts
/** @module Collections */
/** comment */
```

**Comment by pmconne** [comment]
Ended up going with this alternative:
```ts
/** @packageDocumentation
 * @module ModuleName
 */
```

**Comment by christopherthielen** [comment]
fixed in https://github.com/christopherthielen/typedoc-plugin-external-module-name/pull/395/commits/e76b05263d01ccad6e538c651851dcb3c039cfbf

**Comment by christopherthielen** [comment]
released https://github.com/christopherthielen/typedoc-plugin-external-module-name/releases/tag/3.0.0
