### ISSUE TITLE
@preferred comment text missing in module description

### ISSUE THREAD

**Issue by dschoeni** [christopherthielen/typedoc-plugin-external-module-name#5]
When I'm describing a module using `@preferred` like this:

```
/**
 * @module ApiModule
 * @preferred
 * This module yada yada
 */ /** */
```

The text will never show up in the generated typedoc, and in general there doesn't seem to be a way to add a description that the plugin successfully picks up.

When debugging, I found that part of the problem seems to lie [in this line](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/master/plugin.ts#L84), as removing the preferred-tag also gets rid of the text in this specific CommentTag (as typedoc adds the description text to the "CommentTag" object, not the "Comment" itself).

Also, I didn't quite understand why this removal at this place was necessary, as it is done again (?) [down here](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/master/plugin.ts#L135).

I fixed the problem locally by a little hack in the generated JS, right after [this line](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/master/plugin.ts#L124) and by removing the `removeTags` in the `onDeclaration` handler.

```
if (renaming.comment.tags.filter((item) => { return item.tagName == 'preferred'}).length > 0) {
    renaming.comment.text = renaming.comment.tags.filter((item) => { return item.tagName == 'preferred'})[0].text;
}
```

If you are able to reproduce this bug, I'll write a PR to fix the problem for good.
I'm using `typedoc@0.5.5` and the `typedoc-plugin-external-module-name@1.0.8`.

**Comment by dschoeni** [comment]
You can check out https://github.com/dschoeni/typedoc-plugin-external-module-name/tree/fix/module-description for how I tried to fix it for now.

**Comment by wgerven** [comment]
I have the same issue with typedoc@0.5.7 and typedoc-plugin-external-module-name@1.0.8

**Comment by 0v3rst33r** [comment]
When will this make it into the official release pipeline though?

**Comment by Schnjan** [comment]
I must also emphasize to fix the plugin, we need it as a node module.

**Comment by christopherthielen** [comment]
I looked at the suggested change and I think it's not quite what I want to merge to the plugin.  The change indeed allows comments of this form:

```
/**
 * @module asdf
 * @preferred
 * This is my module comment
 */
```

but it doesn't work comments of this form: 

```
/**
 * This is my module comment
 * @module asdf
 * @preferred
 */
```

**Comment by christopherthielen** [comment]
I think the root of this issue is that TypeDoc considers all text after a `@tag` to belong *to the tag*.

**Comment by christopherthielen** [comment]
I created a new plugin `typedoc-plugin-single-line-tags`.  This allows your `@preferred` and `@module` tags to appear anywhere within the comment.

https://github.com/christopherthielen/typedoc-plugin-single-line-tags

These comment styles should all work when using the plugin:

```js
/**
 * @module asdf
 * @preferred
 * This is my module comment
 */
```

```js
/**
 * @module asdf
 * This is my module comment
 * @preferred
 */
```

```js
/**
 * This is my module comment
 * @module asdf
 * @preferred
 * This is an additional module comment
 */
```

**Comment by hobbyguy77** [comment]
I installed both this plugin and the typedoc-plugin-single-line-tags plugin, but module comments still aren't appearing in the generated TypeDoc. I've tried putting the @module and @preferred tags at the beginning/end, but the module's comment still doesn't appear in /modules/modulename.html.

Also, as a side note, if this doesn't work without the second plugin, I'd suggest writing about this on the plugin's main page after "To specify the which file's comment block will be used to document the Typedoc Module page, use @preferred". It's a bit misleading as it is right now.

**Comment by hobbyguy77** [comment]
@christopherthielen, I seem to have found what was wrong: `reflection.comment` was always `undefined` (might be something TypeDoc themselves changed). To get module comments working again, I did the following:
1. Added `import { parseComment} from 'typedoc/dist/lib/converter/factories/comment';` to the list of imports.
2. Changed `onDeclaration` as follows:

```
private onDeclaration(context: Context, reflection: Reflection, node?) {
    if (reflection.kindOf(ReflectionKind.ExternalModule)) {
      let comment = getRawComment(node);
      // Look for @module
      let match = /@module\s+([\w\u4e00-\u9fa5\.\-_/@"]+)/.exec(comment);
      if (match) {
        // Look for @preferred
        let preferred = /@preferred/.exec(comment);
        reflection.comment = parseComment(comment); //This line needs to be added!
        // Set up a list of renames operations to perform when the resolve phase starts
        this.moduleRenames.push({
          renameTo: match[1],
          preferred: preferred != null,
          reflection: <ContainerReflection>reflection,
        });
      }
    }

    if (reflection.comment) {
      CommentPlugin.removeTags(reflection.comment, 'module');
    }
  }
```
3.  Replaced the line `if (item.preferred) mergeTarget.comment = renaming.comment;` with:


```
if (item.preferred) {
        if (renaming.comment){
            let commentTags = renaming.comment.tags.filter((item) => { return item.tagName == 'preferred'});
            
            if (commentTags.length > 0) {
                renaming.comment.text = commentTags[0].text;
            }
        }
        
        mergeTarget.comment = renaming.comment;
    }
```

as @dschoeni suggested. Seems to work now! Thanks, btw, for the plugin! ;-)
