### ISSUE TITLE
Docs generation breaks with custom module name generation when using typedoc v0.19.2

### ISSUE THREAD

**Issue by anmolarora1** [christopherthielen/typedoc-plugin-external-module-name#548]
![Screenshot 2020-10-22 at 2 58 44 PM](https://user-images.githubusercontent.com/7765764/96852935-626e6d80-1477-11eb-9f44-edaa9e5c795b.png)

The `typedoc` generation fails with v0.19.2 when a custom module name generation mapper is used because it's assumed that the `rootFileNames` would always be a non-empty array.
https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/5af43c4189123b63dee3065392a06a7ea5d28126/typedoc-plugin-external-module-name.ts#L103

![Screenshot 2020-10-22 at 2 44 01 PM](https://user-images.githubusercontent.com/7765764/96852082-57670d80-1476-11eb-9c0b-2e262a928d63.png)

There's no such expectation in the method definition in though - check [getRootFileNames](https://github.com/microsoft/TypeScript/blob/15cec9d1f7ef8043cf456fc9a288fc2b3f83f073/src/server/project.ts#L1870) method (taken from Typescript)

As a result, the function breaks unexpectedly when there are no `rootFileNames`

The solution might be fiddlier than it seems, but adding an empty array check on [this line ](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/5af43c4189123b63dee3065392a06a7ea5d28126/typedoc-plugin-external-module-name.ts#L103)prevents unexpected errors for now.

**Comment by christopherthielen** [comment]
The root path auto-detection code assumed you used `files` in your `tsconfig.json` and didn't account for `includes` syntax.
This fix should fall back to using the current directory instead when `includes` is used.

Released in version `4.0.4`

@anmolarora1
