### ISSUE TITLE
Second comment block

### ISSUE THREAD

**Issue by johnjacobkenny** [christopherthielen/typedoc-plugin-external-module-name#6]
From the readme, 
`A known issue: The comment block must be followed by another comment block for some reason (?)`

Is this a typedoc issue or an issue with this plugin? Is there any info on any progress being made to solve it?

Thanks 😄

**Comment by jsdream** [comment]
+1

**Comment by filipsalpe** [comment]
Looks like it comes from typedoc: https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/factories/comment.ts#L91-L93.
No idea why they're doing this but one of the options is reimplementing `getRawComment` in this repo. @christopherthielen I'd be happy to submit a PR if you think this would be the proper solution.

**Comment by christopherthielen** [comment]
If you think it would work, I will def merge it!

**Comment by filipsalpe** [comment]
I considered submitting a PR to typedoc instead, however, it seems that they're intentionally doing this to avoid including stuff like license headers in the docs. PR coming up soon.

**Comment by adrice727** [comment]
I'm still seeing this issue.

**Comment by christopherthielen** [comment]
@adrice727 can you post your repo? I'd like to take a look

**Comment by adrice727** [comment]
@christopherthielen It's currently private, but it should be public in another week or so.

**Comment by christopherthielen** [comment]
Released 1.1.1 which should correctly address this now.  Sorry for the delay
